### ISSUE TITLE
Request about Code

### ISSUE THREAD

**Issue by smiles724** [hehefan/Continuous-Discrete-Convolution#1]
Hi, your CDConv is inspiring and achieves very excellent results. However, your repository only contains the readme file. Do you plan to release all the code?

**Comment by hehefan** [comment]
Hi, will be at the end of April.

**Comment by limei0307** [comment]
Hi, thanks for the great work and for uploading the codes! However, I noticed that the model file is missing. I can't `from models import Model`. Could you add the model file? Thanks!

**Comment by hehefan** [comment]
@limei0307 Uploaded. Sorry for the missing file.
